apiVersion: v1
kind: Service
metadata:
  name:  vishalkumar392-rtp-service
  namespace: vishalkumar392
spec:
  type: NodePort
  selector:
    app: vishalkumar392-rtp
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer